package com.wr.po;

import java.util.Date;

public class BossUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.user_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.user_detail_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String userDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.remark
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.gmt_authorize
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private Date gmtAuthorize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.mobile
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.email
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.gmt_modify_password
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private Date gmtModifyPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.status
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.rote_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String roteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.gmt_modify
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.gmt_last_login
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private Date gmtLastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.gmt_create
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.password
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_user.user_name
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.user_id
     *
     * @return the value of boss_user.user_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.user_id
     *
     * @param userId the value for boss_user.user_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.user_detail_id
     *
     * @return the value of boss_user.user_detail_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getUserDetailId() {
        return userDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.user_detail_id
     *
     * @param userDetailId the value for boss_user.user_detail_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setUserDetailId(String userDetailId) {
        this.userDetailId = userDetailId == null ? null : userDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.remark
     *
     * @return the value of boss_user.remark
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.remark
     *
     * @param remark the value for boss_user.remark
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.gmt_authorize
     *
     * @return the value of boss_user.gmt_authorize
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public Date getGmtAuthorize() {
        return gmtAuthorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.gmt_authorize
     *
     * @param gmtAuthorize the value for boss_user.gmt_authorize
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setGmtAuthorize(Date gmtAuthorize) {
        this.gmtAuthorize = gmtAuthorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.mobile
     *
     * @return the value of boss_user.mobile
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.mobile
     *
     * @param mobile the value for boss_user.mobile
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.email
     *
     * @return the value of boss_user.email
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.email
     *
     * @param email the value for boss_user.email
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.gmt_modify_password
     *
     * @return the value of boss_user.gmt_modify_password
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public Date getGmtModifyPassword() {
        return gmtModifyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.gmt_modify_password
     *
     * @param gmtModifyPassword the value for boss_user.gmt_modify_password
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setGmtModifyPassword(Date gmtModifyPassword) {
        this.gmtModifyPassword = gmtModifyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.status
     *
     * @return the value of boss_user.status
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.status
     *
     * @param status the value for boss_user.status
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.rote_id
     *
     * @return the value of boss_user.rote_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getRoteId() {
        return roteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.rote_id
     *
     * @param roteId the value for boss_user.rote_id
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setRoteId(String roteId) {
        this.roteId = roteId == null ? null : roteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.gmt_modify
     *
     * @return the value of boss_user.gmt_modify
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.gmt_modify
     *
     * @param gmtModify the value for boss_user.gmt_modify
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.gmt_last_login
     *
     * @return the value of boss_user.gmt_last_login
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public Date getGmtLastLogin() {
        return gmtLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.gmt_last_login
     *
     * @param gmtLastLogin the value for boss_user.gmt_last_login
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setGmtLastLogin(Date gmtLastLogin) {
        this.gmtLastLogin = gmtLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.gmt_create
     *
     * @return the value of boss_user.gmt_create
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.gmt_create
     *
     * @param gmtCreate the value for boss_user.gmt_create
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.password
     *
     * @return the value of boss_user.password
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.password
     *
     * @param password the value for boss_user.password
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_user.user_name
     *
     * @return the value of boss_user.user_name
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_user.user_name
     *
     * @param userName the value for boss_user.user_name
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    @Override
    public String toString() {
        return "BossUser{" +
                "userId='" + userId + '\'' +
                ", userDetailId='" + userDetailId + '\'' +
                ", remark='" + remark + '\'' +
                ", gmtAuthorize=" + gmtAuthorize +
                ", mobile='" + mobile + '\'' +
                ", email='" + email + '\'' +
                ", gmtModifyPassword=" + gmtModifyPassword +
                ", status='" + status + '\'' +
                ", roteId='" + roteId + '\'' +
                ", gmtModify=" + gmtModify +
                ", gmtLastLogin=" + gmtLastLogin +
                ", gmtCreate=" + gmtCreate +
                ", password='" + password + '\'' +
                ", userName='" + userName + '\'' +
                '}';
    }
}