package com.wr.dao;

import com.wr.po.BossUser;

import java.util.List;

public interface BossUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_user
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_user
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    int insert(BossUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_user
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    int insertSelective(BossUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_user
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    int updateByPrimaryKeySelective(BossUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_user
     *
     * @mbggenerated Sat Sep 09 12:06:37 CST 2017
     */
    int updateByPrimaryKey(BossUser record);

    BossUser selectByPrimaryKey(String userId);

    List<BossUser> selectByExample(BossUser bossUser);
}